[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "https://invest.carbonecomarket.com/*"
  to = "/invest/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/en"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/invest/en"
  to = "/invest/index.html"
  status = 200
